version: "3.3"
services:
 mongodb:
  container_name: mongo
  image: mongo:latest
  ports:
    - "27017:27017"
 backend:
  container_name: backend
  build: ./Backend
  env_file:
    - ./Backend/.env
  ports:
    - "5000:5000"
  depends_on: 
    - mongodb
 frontend:
  container_name: frontend
  build: ./Frontend
  env_file:
    - ./Frontend/.env
  ports:
    - "5173:5173"
